### PR TITLE
#174 Added .editorconfig and reformatted all java and xml files

### PR DESCRIPTION
**Pull request by HeinrichFilter**
- The reformat was done using IntelliJ's "Reformat Code..." functionality
and "Optimize imports" enabled but "Rearrange entries" disabled.
- Only *.java and *.xml files were formatted by using File masks
- The default IntelliJ Code Style was used with "EditorConfig support"
enabled.

### CODE REVIEW

**Comment by oblonski** [comment]
Hello Heinrich, would you mind to pull the latest version and reformat again? Then I can merge your pull request into the master (this pull here needs a merge, and I think it just easier to reformat it rather than merge it manually). Thanks, Stefan

**Comment by HeinrichFilter** [comment]
I agree, a reformat will be easier. I'll try to do that within a day or two.

Regards,
Heinrich
Co-founder at Intelligent Routing <http://www.intelligentrouting.co.za/>

*YouTube:*
Intelligent Routing at 62 Waters <https://youtu.be/zfmo_m-V2eQ>
Intelligent Routing Overview Animation <https://youtu.be/dT25uNWReAs>

**Comment by oblonski** [comment]
Great! Thanks, Heinrich.

Am 08/09/15 um 09:14 schrieb Heinrich Filter:

**Comment by oblonski** [comment]
Thanks for suggesting this. I just reformatted the projects with your editorconfig suggestion.

**Comment by HeinrichFilter** [comment]
Great, thanks Stefan!

Sorry, that I didn't get to do this, as promised, in the past few days :-/

**Comment by oblonski** [comment]
No problem at all. I thank you for your help.

Am 11/09/15 um 13:01 schrieb Heinrich Filter:

**Pull request closed without merging**
